<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format2.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="2">
  <name>launch_testing_ros_ament_cmake</name>
  <version>0.28.0</version>
  <description>A package providing cmake functions for running ROS 2 enabled launch tests from the build.</description>

  <maintainer email="aditya.pande@openrobotics.org">Aditya Pande</maintainer>
  <maintainer email="brandon@openrobotics.org">Brandon Ong</maintainer>

  <license>Apache License 2.0</license>

  <author email="logans@cottsay.net">Scott K Logan</author>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <buildtool_export_depend>launch_testing_ament_cmake</buildtool_export_depend>
  <buildtool_export_depend>launch_testing_ros</buildtool_export_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>
  <test_depend>launch_testing</test_depend>
  <test_depend>launch_testing_ros</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
